#!/bin/bash

# pico_w
# sudo openocd \
#   -f interface/cmsis-dap.cfg \
#   -f target/rp2040.cfg \
#   -c "adapter speed 5000" \
#   -c "program build-pico_w/pico_https_example.elf verify reset exit"

# pico2_w
sudo openocd \
  -f interface/cmsis-dap.cfg \
  -f target/rp2350.cfg \
  -c "adapter speed 5000" \
  -c "program build-pico2_w/pico_https_example.elf verify reset exit"
